# Generated by Django 3.0.5 on 2020-04-21 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mobsms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_no', models.CharField(max_length=15, validators=[mobsms.models.validatePhone])),
                ('cart', models.TextField()),
                ('total_price', models.IntegerField(validators=[mobsms.models.validatePrice])),
            ],
        ),
        migrations.CreateModel(
            name='phone',
            fields=[
                ('PhoneId', models.AutoField(primary_key=True, serialize=False)),
                ('Brand', models.CharField(default='', max_length=50)),
                ('In_The_Box', models.CharField(default='Handset,Charger,Battery,User Manual', max_length=200)),
                ('Model_Name', models.CharField(default='', max_length=50)),
                ('Model_Number', models.CharField(default='', max_length=50)),
                ('Color', models.CharField(default='', max_length=50)),
                ('Price', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('basic', 'Basic phone'), ('smart', 'Smart phone')], default='basic', max_length=12)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Sim_Type', models.CharField(default='Dual Sim', max_length=50)),
                ('Display_size', models.FloatField(default=0)),
                ('Resolution', models.CharField(default='', max_length=30)),
                ('Front_Image', models.ImageField(default='', upload_to='mobsms/images')),
                ('Back_Image', models.ImageField(default='', upload_to='mobsms/images')),
                ('Other_Image', models.ImageField(blank=True, default='', upload_to='mobsms/images')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='basic',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mobsms.phone')),
                ('Internal_storage', models.IntegerField(default=0)),
                ('Ram', models.IntegerField(default=0)),
                ('Supported_memorycard_type', models.CharField(blank=True, default='', max_length=30)),
                ('Memorycard_slot_type', models.CharField(default='Dedicated Slot', max_length=20, null=True)),
                ('Primary_camera', models.CharField(default='NA', max_length=30, null=True)),
                ('Supported_networks', models.CharField(default='GSM', max_length=90)),
                ('Sim_size', models.CharField(default='Normal SIM', max_length=30)),
                ('Keypad_type', models.CharField(blank=True, default='Alphanumeric', max_length=50)),
                ('Battery_capacity', models.IntegerField(default=0)),
                ('Bluetooth', models.BooleanField(default=True)),
                ('Audiojack', models.BooleanField(default=True)),
                ('Nonremovable_battry', models.BooleanField(default=True)),
            ],
            bases=('mobsms.phone',),
        ),
        migrations.CreateModel(
            name='smart',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mobsms.phone')),
                ('Resolution_type', models.CharField(default='HD', max_length=10)),
                ('Gpu', models.CharField(default='', max_length=40)),
                ('Other_display_features', models.TextField(default='')),
                ('Operating_system', models.CharField(default='', max_length=20)),
                ('Processor_type', models.CharField(default='', max_length=30)),
                ('Processor_core', models.CharField(default='', max_length=20)),
                ('Primary_clock_speed', models.FloatField(default=0)),
                ('Secondary_clock_speed', models.FloatField(blank=True, default=0)),
                ('Internal_storage', models.IntegerField(default=0)),
                ('Ram', models.IntegerField(default=0)),
                ('Expandable_Storage', models.SmallIntegerField(blank=True, default=0)),
                ('Supported_memorycard_type', models.CharField(blank=True, default='', max_length=30)),
                ('Memorycard_slot_type', models.CharField(blank=True, default='Dedicated Slot', max_length=20)),
                ('Primary_camera', models.CharField(default='', max_length=80)),
                ('Primary_camera_features', models.TextField(default='', max_length=200)),
                ('Secondary_camera', models.CharField(blank=True, default='', max_length=60)),
                ('Secondary_camera_features', models.TextField(default='', max_length=150)),
                ('Flash', models.CharField(default='', max_length=40)),
                ('Dual_camera_lens', models.CharField(default='', max_length=60)),
                ('Supported_networks', models.CharField(default='WCDMA, GSM', max_length=90)),
                ('Internet_connectivity', models.CharField(default='', max_length=50)),
                ('Bluetooth_version', models.FloatField(default=4.0)),
                ('Touchscreen_type', models.CharField(default='Multi-touch', max_length=50)),
                ('Sim_size', models.CharField(default='Dual Nano SIM', max_length=30)),
                ('User_interface', models.CharField(default='', max_length=50)),
                ('Weight', models.IntegerField(default=0)),
                ('Sensors', models.CharField(default='', max_length=200)),
                ('Other_features', models.TextField(default='')),
                ('Battery_capacity', models.IntegerField(default=0)),
                ('Battery_type', models.CharField(blank=True, default='', max_length=50)),
                ('Bluetooth', models.BooleanField(default=True)),
                ('Audiojack', models.BooleanField(default=True)),
                ('Nonremovable_battry', models.BooleanField(default=True)),
                ('Otg_compatible', models.BooleanField(default=True)),
            ],
            bases=('mobsms.phone',),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=12, validators=[mobsms.models.validatePhone])),
                ('DOB', models.DateField(blank=True, null=True, validators=[mobsms.models.validateDate])),
                ('image', models.ImageField(default='profile_pic/default.jpg', upload_to='profile_pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
