# Generated by Django 3.0.5 on 2020-04-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobsms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basic',
            old_name='Nonremovable_battry',
            new_name='Nonremovable_battery',
        ),
        migrations.RenameField(
            model_name='smart',
            old_name='Nonremovable_battry',
            new_name='Nonremovable_battery',
        ),
    ]
