# Generated by Django 3.0.5 on 2020-04-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobsms', '0003_auto_20200421_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='Back_Image',
            new_name='Back_image',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='Front_Image',
            new_name='Front_image',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='Other_Image',
            new_name='Other_image',
        ),
    ]
