# Generated by Django 3.0.5 on 2020-04-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobsms', '0004_auto_20200421_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='Sim_Type',
            new_name='Sim_type',
        ),
        migrations.AlterField(
            model_name='basic',
            name='Keypad_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='basic',
            name='Primary_camera',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Display_size',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Bluetooth_version',
            field=models.FloatField(blank=True, default=4.0),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Touchscreen_type',
            field=models.CharField(blank=True, default='Multi-touch', max_length=50),
        ),
    ]
