# Generated by Django 3.0.5 on 2020-04-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobsms', '0005_auto_20200422_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='In_The_Box',
            new_name='In_the_box',
        ),
    ]
