# Generated by Django 3.0.5 on 2020-04-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobsms', '0006_auto_20200422_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smart',
            old_name='Expandable_Storage',
            new_name='Expandable_storage',
        ),
    ]
