# Generated by Django 3.0.5 on 2020-04-22 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mobsms', '0007_auto_20200422_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
