# Generated by Django 3.0.5 on 2020-04-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobsms', '0010_auto_20200422_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smart',
            name='Primary_camera_features',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Secondary_camera_features',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
