# Generated by Django 3.0.5 on 2020-04-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobsms', '0011_auto_20200423_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic',
            name='Memorycard_slot_type',
            field=models.CharField(default='Dedicated Slot', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='basic',
            name='Sim_size',
            field=models.CharField(default='Normal SIM', max_length=50),
        ),
        migrations.AlterField(
            model_name='basic',
            name='Supported_networks',
            field=models.CharField(default='GSM', max_length=120),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Display_size',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='phone',
            name='In_the_box',
            field=models.CharField(default='Handset,Charger,Battery,User Manual', max_length=400),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Model_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Model_number',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Gpu',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Internal_storage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Operating_system',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Processor_core',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Processor_type',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Ram',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Secondary_clock_speed',
            field=models.FloatField(blank=True),
        ),
    ]
