# Generated by Django 3.0.5 on 2020-04-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobsms', '0012_auto_20200423_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic',
            name='Battery_capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='basic',
            name='Internal_storage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='basic',
            name='Ram',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Battery_capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Battery_type',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Expandable_storage',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Internet_connectivity',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Memorycard_slot_type',
            field=models.CharField(blank=True, default='Dedicated Slot', max_length=30),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Sensors',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Sim_size',
            field=models.CharField(default='Dual Nano SIM', max_length=50),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Touchscreen_type',
            field=models.CharField(blank=True, default='Multi-touch', max_length=60),
        ),
        migrations.AlterField(
            model_name='smart',
            name='User_interface',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Weight',
            field=models.IntegerField(blank=True),
        ),
    ]
