# Generated by Django 3.0.5 on 2020-04-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobsms', '0014_auto_20200423_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smart',
            name='Expandable_storage',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
