# Generated by Django 3.0.5 on 2020-04-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobsms', '0015_auto_20200423_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smart',
            name='Bluetooth_version',
            field=models.FloatField(blank=True, default=4.0, null=True),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
