# Generated by Django 3.0.5 on 2020-04-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobsms', '0016_auto_20200423_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smart',
            name='Primary_camera_features',
            field=models.TextField(default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Secondary_camera_features',
            field=models.TextField(default='', max_length=1500),
        ),
    ]
