# Generated by Django 3.0.5 on 2020-04-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobsms', '0017_auto_20200423_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='Other_image2',
            field=models.ImageField(blank=True, default='', upload_to='mobsms/images'),
        ),
    ]
