# Generated by Django 3.0.5 on 2020-04-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobsms', '0018_phone_other_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smart',
            name='Secondary_clock_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
