# Generated by Django 3.0.5 on 2020-04-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobsms', '0019_auto_20200423_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smart',
            name='Dual_camera_lens',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Secondary_camera_features',
            field=models.TextField(blank=True, default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='smart',
            name='Sensors',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
