# Generated by Django 3.0.5 on 2020-04-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobsms', '0020_auto_20200424_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smart',
            name='Gpu',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='smart',
            name='User_interface',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
