# Generated by Django 3.0.5 on 2020-04-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobsms', '0021_auto_20200424_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic',
            name='Ram',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
