# Generated by Django 3.0.5 on 2020-04-28 15:59

from django.db import migrations, models
import mobsms.models


class Migration(migrations.Migration):

    dependencies = [
        ('mobsms', '0023_auto_20200427_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic',
            name='Expandable_storage',
            field=models.SmallIntegerField(blank=True, null=True, validators=[mobsms.models.validatePositive]),
        ),
    ]
